# Stage 1: Build the site
FROM node:20-slim AS builder

WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package.json .
COPY package-lock.json* .
RUN npm ci

# Copy the project files (including content) and build the static site
COPY . .

# Run the Quartz build
RUN npx quartz build

# Stage 2: Serve the site with Nginx
FROM nginx:alpine

# Remove the default Nginx site and copy the built site
RUN rm -rf /usr/share/nginx/html/*

# Copy the static files generated by Quartz to Nginx's web directory
COPY --from=builder /usr/src/app/public /usr/share/nginx/html

# Expose port 80 to access the web server
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
